
spring:
  application:
    name: spring-cloud-turbine

server:
  port: 8001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include:  "*"
      base-path:  /actuator  #默认就是/actuator
  endpoint:
    health:
      show-details: ALWAYS

turbine:
  app-config: spring-cloud-consumer,spring-cloud-consumer1
  aggregator:
    cluster-config: default
  cluster-name-expression: new String("default")

