
spring:
  application:
    name: spring-cloud-consumer

  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0


server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include:  "*"
      base-path:  /actuator  #默认就是/actuator
