spring:
  application:
    name: spring-cloud-producer

server:
  port: 9000

eureka:
  instance:
    hostname: ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
