
spring:
  application:
    name: spring-cloud-consumer1

server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include:  "*"
      base-path:  /actuator  #默认就是/actuator
